# Generated by Django 5.0.3 on 2025-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basvuru_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasaport_turu', models.CharField(max_length=30)),
                ('tc_no', models.IntegerField()),
                ('isim_soyisim', models.CharField(max_length=30)),
                ('kadro_unvani', models.CharField(max_length=30)),
                ('kurum_sicil_no', models.IntegerField()),
                ('tel_no', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('nufus_mudurluk', models.CharField(max_length=40)),
                ('cocuk_sayisi', models.IntegerField()),
                
            ],
        ),
    ]
