# Generated by Django 5.0.3 on 2025-03-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basvuru_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru_details',
            name='onay',
            field=models.BooleanField(default=False),
        ),
    ]
