# Generated by Django 5.0.3 on 2025-03-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basvuru_app', '0002_basvuru_details_onay'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru_details',
            name='gerekce',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
